apiVersion: v1
kind: Secret
metadata:
  name: video-mgmt-db-secrets
  labels:
    app: video-management-service
type: Opaque
data:
  # Note: These are placeholder base64 values. Replace with actual secrets in production.
  # Use: echo -n "value" | base64
  # Example: jdbc:postgresql://postgres-host:5432/streamflix_videos
  jdbc-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtaG9zdDo1NDMyL3N0cmVhbWZsaXhfdmlkZW9z
  username: c3RyZWFtZmxpeF91c2Vy
  password: c3VwZXJTZWNyZXRQYXNzd29yZDEyMyE=
---
apiVersion: v1
kind: Secret
metadata:
  name: video-mgmt-s3-secrets
  labels:
    app: video-management-service
type: Opaque
data:
  # Note: These are placeholder base64 values. Replace with actual secrets in production.
  access-key: QUtJQUlPRk9ESU5OMzRFWEFNUExF
  secret-key: d0phbFIvTGVvTWZZY1BuZUFCQ0RFRkdISUpLTE1OT1BRUVJTVA==
---
apiVersion: v1
kind: Secret
metadata:
  name: video-mgmt-jwt-secrets
  labels:
    app: video-management-service
type: Opaque
data:
  # Note: This is a placeholder base64 value. Replace with actual secret in production.
  jwt-secret: c3VwZXJzZWNyZXRrZXl0aGF0c2hvdWxkYmVsb25nZW5vdWdoYW5kc2VjdXJl
