apiVersion: v2
name: video-mgmt
description: Video Management Service Helm Chart for Streamflix Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Streamflix Team
    email: devops@streamflix.example.com
dependencies:
  - name: postgresql
    version: "~12.5.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~17.11.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
