apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: streamflix-staging

resources:
- ../../base

patches:
- path: patches/deployment-patch.yaml

configMapGenerator:
- name: streamflix-auth-config
  behavior: merge
  literals:
  - NODE_ENV=staging
  - DB_HOST=staging-postgres-service
  - TRACING_ENABLED=true
  - PROMETHEUS_ENABLED=true