services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        volumes:
            - ./build/reports:/app/build/reports
            - ./build/test-results:/app/build/test-results
        environment:
            - SPRING_PROFILES_ACTIVE=test
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/streamflix_test
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=streamflix_test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-test-data:/var/lib/postgresql/data

volumes:
    postgres-test-data:
