version: "3.8"

services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        volumes:
            - ./build/reports:/app/build/reports
            - ./build/test-results:/app/build/test-results
        environment:
            - SPRING_PROFILES_ACTIVE=test
