global:
  resolve_timeout: 5m
  smtp_from: 'alerts@streamflix.com'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'alerts@streamflix.com'
  smtp_auth_password: 'password'

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for all alerts
  # Alerts that don't match any child routes will be assigned to this route
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'team-auth'
  routes:
  - match:
      severity: critical
    receiver: 'team-auth-pager'
    continue: true
  - match_re:
      service: auth.*
    receiver: 'team-auth'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

receivers:
- name: 'team-auth'
  email_configs:
  - to: 'auth-team@streamflix.com'
    send_resolved: true

- name: 'team-auth-pager'
  email_configs:
  - to: 'auth-team-pager@streamflix.com'
    send_resolved: true