global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# A scrape configuration containing endpoints to scrape:
scrape_configs:
  # Auth service metrics
  - job_name: 'auth-service'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['auth-service:3000']
        labels:
          service: 'streamflix-auth-service'
          environment: 'development'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for host metrics
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']