apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-mgmt.fullname" . }}-config
  labels:
    {{- include "video-mgmt.labels" . | nindent 4 }}
data:
  # Application configuration
  application.yml: |
    spring:
      profiles:
        active: {{ .Values.springBoot.profile }}
      kafka:
        bootstrap-servers: {{ .Values.kafka.servers }}
      cloud:
        stream:
          kafka:
            binder:
              brokers: {{ .Values.kafka.servers }}
      redis:
        host: {{ .Values.redis.host }}
        port: {{ .Values.redis.port }}

    # Custom Kafka topic configuration
    kafka:
      topics:
        video-created: {{ .Values.kafka.topics.videoCreated }}
        video-updated: {{ .Values.kafka.topics.videoUpdated }}
        video-deleted: {{ .Values.kafka.topics.videoDeleted }}
        video-status-changed: {{ .Values.kafka.topics.videoStatusChanged }}
        video-processing-requested: {{ .Values.kafka.topics.videoProcessingRequested }}

    # Service configuration values
    server:
      port: {{ .Values.service.port }}
      shutdown: graceful
      tomcat:
        max-threads: 200
        min-spare-threads: 20
    spring.lifecycle.timeout-per-shutdown-phase: 30s

    # Observability configuration
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
