apiVersion: v1
kind: ConfigMap
metadata:
  name: streamflix-auth-config
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "streamflix_auth"
  DB_SCHEMA: "public"
  DB_CONNECTION_POOL_SIZE: "20"
  JWT_ACCESS_EXPIRATION: "3600"
  JWT_REFRESH_EXPIRATION: "604800"
  PASSWORD_HASH_ROUNDS: "12"
  RATE_LIMIT_TTL: "60"
  RATE_LIMIT_MAX: "100"
  TRACING_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"