spring:
  application:
    name: video-management-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/streamflix_videos
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: video-management-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  
  # Spring Cloud Stream Configuration
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
      bindings:
        video-created-out:
          destination: ${kafka.topics.video-created}
          content-type: application/json
        video-updated-out:
          destination: ${kafka.topics.video-updated}
          content-type: application/json
        video-deleted-out:
          destination: ${kafka.topics.video-deleted}
          content-type: application/json
        video-status-changed-out:
          destination: ${kafka.topics.video-status-changed}
          content-type: application/json
        video-processing-requested-out:
          destination: ${kafka.topics.video-processing-requested}
          content-type: application/json
  
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom Kafka topic configuration
kafka:
  topics:
    video-created: streamflix.videos.created
    video-updated: streamflix.videos.updated
    video-deleted: streamflix.videos.deleted
    video-status-changed: streamflix.videos.status-changed
    video-processing-requested: streamflix.videos.processing-requested

# S3 storage configuration
cloud:
  aws:
    s3:
      endpoint: ${S3_ENDPOINT:http://localhost:9000}
      region: ${S3_REGION:us-east-1}
      bucket-name: ${S3_BUCKET_NAME:streamflix-videos}
      access-key: ${S3_ACCESS_KEY:minioadmin}
      secret-key: ${S3_SECRET_KEY:minioadmin}
      presigned-url-expiration: ${S3_PRESIGNED_URL_EXPIRATION:3600}

# Security configuration
streamflix:
  security:
    jwt:
      secret: ${JWT_SECRET:supersecretkeythatshouldbesecure}
      expiration: 86400000  # 24 hours in milliseconds