apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: streamflix-prod

resources:
- ../../base

patches:
- path: patches/deployment-patch.yaml
- path: patches/hpa-patch.yaml

configMapGenerator:
- name: streamflix-auth-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - DB_HOST=prod-postgres-service
  - TRACING_ENABLED=true
  - PROMETHEUS_ENABLED=true
  - RATE_LIMIT_TTL=30
  - RATE_LIMIT_MAX=50